### ISSUE TITLE
Update Requirements: `numpy` missing

### ISSUE THREAD

**Issue by GeorgeBatch** [kdexd/virtex#29] opened 2021-11-23 12:03 UTC
Dear authors,

Thank you very much for providing the code and instructions for using this library! I tried to use the instructions from http://kdexd.xyz/virtex/virtex/usage/setup_dependencies.html:

```{shell}
cd virtex
conda create -n virtex python=3.6
conda activate virtex
pip install -r requirements.txt
```

I run into a problem that numpy was not found when I ran `pip install -r requirements.txt`.
I fixed it by running `conda install numpy` before that.

Maybe you could add it to the `requirements.txt` so others can use the same version you used.

Many thanks,
George Batchkala

**Comment by kdexd** [comment] 2021-12-19 01:33
Hi @GeorgeBatch, we usually rely on whatever numpy version `torch` requires. But this is a good idea – I will just add this dependency.

**Comment by kdexd** [comment] 2021-12-19 01:37
Hi @GeorgeBatch – I cannot reproduce this issue, `numpy` already exists in requirements and I could install it with `pip install -r requirements.txt`. I will close this issue, you seem to have found some fix to unblock your work! Feel free to re-open it if you face any issues related to this later!

**Closed by kdexd** 2021-12-19 01:37 UTC
